### ISSUE TITLE
error[E0554]: `#![feature]` may not be used on the stable release channel

### ISSUE THREAD

**Issue by lexcorp** [w-henderson/Kascreech#6]
[root@zmanda server]# cargo run --verbose
       Fresh unicode-xid v0.2.2
       Fresh cfg-if v1.0.0
       Fresh autocfg v1.0.1
       Fresh version_check v0.9.3
       Fresh slab v0.4.3
       Fresh lazy_static v1.4.0
       Fresh futures-sink v0.3.15
       Fresh cfg-if v0.1.10
       Fresh pin-project-lite v0.2.6
       Fresh futures-io v0.3.15
       Fresh pin-project-lite v0.1.12
       Fresh bytes v0.5.6
       Fresh pin-utils v0.1.0
       Fresh smallvec v1.6.1
       Fresh scopeguard v1.1.0
       Fresh matches v0.1.8
       Fresh convert_case v0.4.0
       Fresh percent-encoding v2.1.0
       Fresh tinyvec_macros v0.1.0
       Fresh itoa v0.4.7
       Fresh copyless v0.1.5
       Fresh unicode-segmentation v1.7.1
       Fresh ppv-lite86 v0.2.10
       Fresh either v1.6.1
       Fresh bytes v1.0.1
       Fresh cc v1.0.67
       Fresh match_cfg v0.1.0
       Fresh fnv v1.0.7
       Fresh quick-error v1.2.3
       Fresh linked-hash-map v0.5.4
       Fresh hashbrown v0.9.1
       Fresh adler v1.0.2
       Fresh version_check v0.1.5
       Fresh regex-syntax v0.6.25
       Fresh mime v0.3.16
       Fresh byteorder v1.4.3
       Fresh cpufeatures v0.1.4
       Fresh opaque-debug v0.3.0
       Fresh language-tags v0.2.2
       Fresh base64 v0.13.0
       Fresh bytes v0.6.0
       Fresh once_cell v1.7.2
       Fresh fastrand v1.4.1
       Fresh instant v0.1.9
       Fresh tracing-core v0.1.18
       Fresh lock_api v0.4.4
       Fresh unicode-bidi v0.3.5
       Fresh form_urlencoded v1.0.1
       Fresh tinyvec v1.2.0
       Fresh heck v0.3.2
       Fresh bytestring v1.0.0
       Fresh http v0.2.4
       Fresh lru-cache v0.1.2
       Fresh fxhash v0.2.1
       Fresh buf-min v0.2.0
       Fresh proc-macro2 v1.0.26
       Fresh libc v0.2.94
       Fresh memchr v2.4.0
       Fresh log v0.4.14
       Fresh proc-macro-hack v0.5.19
       Fresh futures-core v0.3.15
       Fresh proc-macro-nested v0.1.7
       Fresh futures-task v0.3.15
       Fresh bitflags v1.2.1
       Fresh unicode-normalization v0.1.17
       Fresh typenum v1.13.0
       Fresh ryu v1.0.5
       Fresh const_fn v0.4.7
       Fresh crc32fast v1.2.1
       Fresh httparse v1.4.1
       Fresh encoding_rs v0.8.28
       Fresh quote v1.0.9
       Fresh net2 v0.2.37
       Fresh iovec v0.1.4
       Fresh signal-hook-registry v1.3.0
       Fresh parking_lot_core v0.8.3
       Fresh num_cpus v1.13.0
       Fresh getrandom v0.1.16
       Fresh hostname v0.3.1
       Fresh aho-corasick v0.7.18
       Fresh socket2 v0.3.19
       Fresh indexmap v1.6.2
       Fresh miniz_oxide v0.4.4
       Fresh standback v0.2.17
       Fresh tracing v0.1.26
       Fresh unicase v2.6.0
       Fresh futures-channel v0.3.15
       Fresh idna v0.2.3
       Fresh generic-array v0.14.4
       Fresh brotli-sys v0.3.2
       Fresh nom v4.2.3
       Fresh syn v1.0.72
       Fresh mio v0.6.23
       Fresh threadpool v1.8.1
       Fresh parking_lot v0.11.1
       Fresh rand_core v0.5.1
       Fresh resolv-conf v0.7.0
       Fresh regex v1.5.4
       Fresh flate2 v1.0.20
       Fresh url v2.2.2
       Fresh block-buffer v0.9.0
       Fresh digest v0.9.0
       Fresh brotli2 v0.3.2
       Fresh mio-uds v0.6.8
       Fresh futures-macro v0.3.15
       Fresh pin-project-internal v0.4.28
       Fresh derive_more v0.99.14
       Fresh actix-macros v0.1.3
       Fresh serde_derive v1.0.126
       Fresh thiserror-impl v1.0.24
       Fresh time-macros-impl v0.1.1
       Fresh pin-project-internal v1.0.7
       Fresh async-trait v0.1.50
       Fresh enum-as-inner v0.3.3
       Fresh actix-web-codegen v0.4.0
       Fresh v_escape_derive v0.8.4
       Fresh rand_chacha v0.2.2
       Fresh sha-1 v0.9.6
       Fresh tokio v0.2.25
       Fresh futures-util v0.3.15
       Fresh pin-project v0.4.28
       Fresh actix-threadpool v0.3.3
       Fresh serde v1.0.126
       Fresh thiserror v1.0.24
       Fresh time-macros v0.1.1
       Fresh pin-project v1.0.7
       Fresh v_escape v0.14.1
       Fresh rand v0.7.3
       Fresh mime_guess v2.0.3
       Fresh tokio-util v0.3.1
       Fresh actix-service v1.0.6
       Fresh futures v0.3.15
       Fresh actix-rt v1.1.1
       Fresh serde_urlencoded v0.7.0
       Fresh serde_json v1.0.64
       Fresh actix-router v0.2.7
       Fresh time v0.2.26
       Fresh tracing-futures v0.2.5
       Fresh v_htmlescape v0.11.0
       Fresh actix-codec v0.3.0
       Fresh trust-dns-proto v0.19.7
       Fresh cookie v0.14.4
       Fresh h2 v0.2.7
       Fresh actix-utils v2.0.0
       Fresh trust-dns-resolver v0.19.7
       Fresh actix-connect v2.0.0
       Fresh actix-server v1.0.4
       Fresh actix-tls v2.0.0
       Fresh actix-http v2.2.0
       Fresh actix-testing v1.0.1
       Fresh awc v2.0.3
       Fresh actix-web v3.3.2
       Fresh actix-cors v0.5.4
       Fresh actix-files v0.4.1
   Compiling server v0.1.0 (/var/www/html/Kascreech/server)
     Running `rustc --crate-name server --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=6f1b4ff6a6c682cf -C extra-filename=-6f1b4ff6a6c682cf --out-dir /var/www/html/Kascreech/server/target/debug/deps -C incremental=/var/www/html/Kascreech/server/target/debug/incremental -L dependency=/var/www/html/Kascreech/server/target/debug/deps --extern actix_cors=/var/www/html/Kascreech/server/target/debug/deps/libactix_cors-07e3ff62ccce64e4.rlib --extern actix_files=/var/www/html/Kascreech/server/target/debug/deps/libactix_files-1c4575eae6972461.rlib --extern actix_web=/var/www/html/Kascreech/server/target/debug/deps/libactix_web-9545ea505ec1c35b.rlib --extern fastrand=/var/www/html/Kascreech/server/target/debug/deps/libfastrand-5269f8b8a8e12999.rlib --extern serde=/var/www/html/Kascreech/server/target/debug/deps/libserde-11df8d6276dc785e.rlib --extern serde_json=/var/www/html/Kascreech/server/target/debug/deps/libserde_json-5a14a89a08640a3a.rlib -L native=/var/www/html/Kascreech/server/target/debug/build/brotli-sys-48176562eaa37722/out`
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:1:1
  |
1 | #![feature(drain_filter)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `server`

Caused by:
  process didn't exit successfully: `rustc --crate-name server --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=6f1b4ff6a6c682cf -C extra-filename=-6f1b4ff6a6c682cf --out-dir /var/www/html/Kascreech/server/target/debug/deps -C incremental=/var/www/html/Kascreech/server/target/debug/incremental -L dependency=/var/www/html/Kascreech/server/target/debug/deps --extern actix_cors=/var/www/html/Kascreech/server/target/debug/deps/libactix_cors-07e3ff62ccce64e4.rlib --extern actix_files=/var/www/html/Kascreech/server/target/debug/deps/libactix_files-1c4575eae6972461.rlib --extern actix_web=/var/www/html/Kascreech/server/target/debug/deps/libactix_web-9545ea505ec1c35b.rlib --extern fastrand=/var/www/html/Kascreech/server/target/debug/deps/libfastrand-5269f8b8a8e12999.rlib --extern serde=/var/www/html/Kascreech/server/target/debug/deps/libserde-11df8d6276dc785e.rlib --extern serde_json=/var/www/html/Kascreech/server/target/debug/deps/libserde_json-5a14a89a08640a3a.rlib -L native=/var/www/html/Kascreech/server/target/debug/build/brotli-sys-48176562eaa37722/out` (exit code: 1)

**Comment by w-henderson** [comment]
As I said in your last issue (#5), you need Rust Nightly to build and run Kascreech. Please set the toolchain for Kascreech to Nightly by using `rustup override set nightly` in the project directory.
