### ISSUE TITLE
Run server on different port to 80?

### ISSUE THREAD

**Issue by lexcorp** [w-henderson/Kascreech#7]
It's possible run server on different port to 80?

**Comment by w-henderson** [comment]
For some reason it defaults to 8080 (I thought it defaulted to 80 but @flauntingspade4 must've changed it). You can simply change the port the server is bound to at the end of [`server/src/main.rs`](https://github.com/w-henderson/Kascreech/blob/master/server/src/main.rs). This could be added as a command-line argument but this project is pretty much discontinued so I don't plan to make any changes.

If you want to open a PR and add that feature, please go ahead!

**Comment by lexcorp** [comment]
**"but this project is pretty much discontinued so I don't plan to make any changes"** 

it's a shame, it's a good project...

**Comment by lexcorp** [comment]
There are not many good options for this type of project, the only ones that come close are this:

https://github.com/sanity-io/squizzy

and Kascreech

**Comment by w-henderson** [comment]
It might look good but as soon as you look at the code it certainly isn't! We quickly hacked it together as a joke - if it were to become a long-term project the whole thing would need to be refactored (and I'd probably switch Rust out for Firebase) and I don't have the time for that! If you want to do some development on the project feel free to though.

**Comment by lexcorp** [comment]
cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.27s
     Running `target/debug/server`
Error: Os { code: 98, kind: AddrInUse, message: "Address already in use" }

**Comment by lexcorp** [comment]
![image](https://user-images.githubusercontent.com/5751288/118535448-1b481280-b710-11eb-9786-8181efb5aa70.png)

Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.min.js:2 POST https://10.120.7.75/chungusGameInfo 404 (Not Found)

**Comment by lexcorp** [comment]
> cargo run
> Finished dev [unoptimized + debuginfo] target(s) in 0.27s
> Running `target/debug/server`
> Error: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
> 
> How to stop server?
> 
> When I run the server, I get message:
> 
> Error: Os { code: 98, kind: AddrInUse, message: "Address already in use" }

After change port, run sucessfully...

**Comment by w-henderson** [comment]
I can see in your image that your URL is `/Kascreech/web/chungus.html` but you should be at `/chungus.html`. You may need to run `cargo run` from a different directory or something.

**Comment by w-henderson** [comment]
It's been a while @lexcorp but we've finally re-written the whole project from scratch in a much better way! You can now select the address and port to bind the server to when you run the server, for example `kascreech 0.0.0.0:8000` would run it on port 8000.
