### ISSUE TITLE
elliot did large ooooof (Create a lobby)

### ISSUE THREAD

**Issue by lexcorp** [w-henderson/Kascreech#8]
When I try create a lobby, I get this message:

![image](https://user-images.githubusercontent.com/5751288/118530606-74ad4300-b70a-11eb-99a6-bce42723e7a5.png)

**Comment by w-henderson** [comment]
The message says that Elliot did a large oof so I'll assign this issue to him.

**Comment by w-henderson** [comment]
The issue is that you need to set the `SERVER_IP` constant in `chungus.ts` and `client.ts` and then recompile them as described in the README.

**Comment by lexcorp** [comment]
Thanks...
